---
version: '3.8'

services:
  database:
    image: mysql:8.4
    container_name: wow-database
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/create_mysql.sql:/docker-entrypoint-initdb.d/create_mysql.sql
    ports:
      - "3306:3306"
    networks:
      - wow-network
    healthcheck:
      test:
        - "CMD"
        - "mysqladmin"
        - "ping"
        - "-h"
        - "localhost"
        - "-u"
        - "root"
        - "-ppassword123"
      interval: 5s
      timeout: 5s
      retries: 10

  authserver:
    image: ghcr.io/sgumil/wotlk-server/wotlk-server:main
    container_name: wow-auth
    depends_on:
      database:
        condition: service_healthy
    command: ["./authserver"]
    volumes:
      - ./server/etc:/opt/server/etc
    ports:
      - "3724:3724"
    stdin_open: true
    tty: true
    networks:
      - wow-network

  worldserver:
    image: ghcr.io/sgumil/wotlk-server/wotlk-server:main
    container_name: wow-world
    depends_on:
      database:
        condition: service_healthy
    command: ["./worldserver"]
    volumes:
      - ./server/etc:/opt/server/etc
      - ./data:/opt/server/data
      - ./database/TDB_full_world_335.25101_2025_10_21.sql:/opt/server/bin/TDB_full_world_335.25101_2025_10_21.sql
    ports:
      - "8085:8085"
    stdin_open: true
    tty: true
    networks:
      - wow-network

networks:
  wow-network:
